### ISSUE TITLE
A user can create a posting

### ISSUE THREAD

**Issue by florianschmidt1994** [BreakOutEvent/breakout-android#13]

**Comment by fkienhoefer** [comment]
UI for this part ist done. 
As of yet it is just a dummy, but adding functionality is high priority and should be possible in the next 1-2 weeks.

**Comment by florianschmidt1994** [comment]
- [ ] Screen is there
- [ ] Add network requests for this

@fkienhoefer please tell us where the pull request for this is

**Comment by florianschmidt1994** [comment]
Done
